-- MySQL Script generated by MySQL Workbench
-- Tue Apr  4 18:01:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TB_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Endereco` (
  `ID_Endereco` INT NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `Cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Usuario` (
  `ID_Usuario` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL COMMENT 'Este é o campo de nome com o Datatype Varchar de 45',
  `Cpf` VARCHAR(45) NOT NULL,
  `Rg` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `Data_Nascimento` VARCHAR(45) NOT NULL,
  `Nacionalidade` VARCHAR(45) NOT NULL,
  `Estado_Civil` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `TB_Endereco_ID_Endereco` INT NOT NULL,
  PRIMARY KEY (`ID_Usuario`),
  INDEX `fk_TB_Usuario_TB_Endereco_idx` (`TB_Endereco_ID_Endereco` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Usuario_TB_Endereco`
    FOREIGN KEY (`TB_Endereco_ID_Endereco`)
    REFERENCES `mydb`.`TB_Endereco` (`ID_Endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Celular` (
  `ID_Celular` INT NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Celular`),
  UNIQUE INDEX `ID_Celular_UNIQUE` (`ID_Celular` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Vacina` (
  `ID_Vacina` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Fábrica` VARCHAR(45) NOT NULL,
  `Data Fabricacao` VARCHAR(45) NOT NULL,
  `Data Vencimento` VARCHAR(45) NOT NULL,
  `Lote` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `Pais de origem` VARCHAR(45) NOT NULL,
  `TB_Usuario_ID_Usuario` INT NOT NULL,
  PRIMARY KEY (`ID_Vacina`),
  INDEX `fk_TB_Vacina_TB_Usuario1_idx` (`TB_Usuario_ID_Usuario` ASC) VISIBLE,
  UNIQUE INDEX `ID_Vacina_UNIQUE` (`ID_Vacina` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Vacina_TB_Usuario1`
    FOREIGN KEY (`TB_Usuario_ID_Usuario`)
    REFERENCES `mydb`.`TB_Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TB_Usuario_has_TB_Celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TB_Usuario_has_TB_Celular` (
  `TB_Usuario_ID_Usuario` INT NOT NULL,
  `TB_Celular_ID_Celular` INT NOT NULL,
  PRIMARY KEY (`TB_Usuario_ID_Usuario`, `TB_Celular_ID_Celular`),
  INDEX `fk_TB_Usuario_has_TB_Celular_TB_Celular1_idx` (`TB_Celular_ID_Celular` ASC) VISIBLE,
  INDEX `fk_TB_Usuario_has_TB_Celular_TB_Usuario1_idx` (`TB_Usuario_ID_Usuario` ASC) VISIBLE,
  CONSTRAINT `fk_TB_Usuario_has_TB_Celular_TB_Usuario1`
    FOREIGN KEY (`TB_Usuario_ID_Usuario`)
    REFERENCES `mydb`.`TB_Usuario` (`ID_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Usuario_has_TB_Celular_TB_Celular1`
    FOREIGN KEY (`TB_Celular_ID_Celular`)
    REFERENCES `mydb`.`TB_Celular` (`ID_Celular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
